# Generated by Django 5.1.2 on 2024-10-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
        ('users', '0002_remove_user_accesstoken_remove_user_refreshtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='users.user'),
            preserve_default=False,
        ),
    ]
